[package]
name = "proof_of_funds"
type = "bin"
authors = ["Lumengate"]
compiler_version = ">=1.0.0"

[dependencies]
poseidon = { tag = "v0.2.0", git = "https://github.com/noir-lang/poseidon" }
